use_frameworks!

platform :ios, '12.1'

target 'BroadCastExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Broadcast Extension
  pod 'BroadcastPod', '~> 1.0.0'
  
end

target 'BroadcastPod_Example' do
  pod 'BroadcastPod', '~> 1.0.0'

  target 'BroadcastPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
