use_frameworks!

platform :ios, '9.0'

target 'BroadcastPod_Example' do
  pod 'BroadcastPod', :path => '../'

  target 'BroadcastPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
